Repository ava-labs/coreth, pull requests merged in 2024-07, with the labels that each got.

#594 Update to latest p2p API
  go.mod
  go.sum
  peer/network_test.go
  plugin/evm/gossip.go
  scripts/versions.sh
Labels: enhancement

#595 Fix VM.GetBlockIDAtHeight
  plugin/evm/vm.go
  plugin/evm/vm_test.go
Labels: cleanup

#598 [ci] Add actionlint job
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  scripts/actionlint.sh
Labels: testing

#606 Use `avax.GetAtomicUTXOs`
  plugin/evm/vm.go
Labels: cleanup
