Repository ava-labs/coreth, pull requests merged in 2025-10, with the labels that each got.

#1263 ACP-226: add min delay excess to block and verify
  .github/workflows/ci.yml
  consensus/dummy/consensus.go
  core/genesis.go
  core/genesis_extra_test.go
  core/genesis_test.go
  go.mod
  go.sum
  internal/ethapi/testdata/eth_getBlockByHash-hash-1.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-genesis.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-latest-1-fullTx.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-latest.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-0.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-1.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-latest-1.json
  internal/ethapi/testdata/eth_getBlockByNumber-tag-latest.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-blob-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-contract-create-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-dynamic-fee-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-contract-call-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-transfer-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-tag-latest.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-0.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-1.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-latest-1.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-latest.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-0.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-1.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-latest-1.json
  internal/ethapi/testdata/eth_getHeaderByNumber-tag-latest.json
  internal/ethapi/testdata/eth_getTransactionReceipt-blob-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-with-access-list.json
  internal/ethapi/testdata/eth_getTransactionReceipt-dynamic-tx-with-logs.json
  internal/ethapi/testdata/eth_getTransactionReceipt-normal-transfer-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-with-logs.json
  plugin/evm/config/config.go
  plugin/evm/customheader/min_delay_excess.go
  plugin/evm/customheader/min_delay_excess_test.go
  plugin/evm/customtypes/block_ext.go
  plugin/evm/customtypes/block_ext_test.go
  plugin/evm/customtypes/block_test.go
  plugin/evm/customtypes/header_ext.go
  plugin/evm/customtypes/header_ext_test.go
  plugin/evm/vm.go
  plugin/evm/vm_test.go
  plugin/evm/wrapped_block.go
  utils/utilstest/pointer.go
Labels: acp-226

#1311 Add warp test to verify equivalent gas consumed
  precompile/contracts/warp/predicate_test.go
Labels: acp181

#1295 Enforce block building delay only for retries
  plugin/evm/atomic/vm/vm_test.go
  plugin/evm/block_builder.go
  plugin/evm/vm.go
  plugin/evm/vm_test.go
Labels: acp-226

#1313 Remove secondary validator override
  plugin/evm/vm.go
  warp/service.go
Labels: bug, acp181

#1317 chore: Use go 1.24's 'go tool' support for CLI tooling
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  Taskfile.yml
  bin/ginkgo
  core/genesis.go
  eth/ethconfig/config.go
  go.mod
  internal/ethapi/mocks_generate_test.go
  plugin/evm/customtypes/header_ext.go
  precompile/contract/mocks_generate_test.go
  precompile/precompileconfig/mocks_generate_test.go
  scripts/actionlint.sh
  scripts/lint.sh
  scripts/run_ginkgo.sh
  scripts/run_task.sh
  tests/warp/aggregator/mocks_generate_test.go
  tools/go.mod
  tools/go.sum
  tools/legacy-golangci-lint.mod
  tools/legacy-golangci-lint.sum
Labels: dependencies, ci

#1324 Replace `getValidatorSet`
  plugin/evm/vm_warp_test.go
  precompile/contracts/warp/config.go
  precompile/contracts/warp/predicate_test.go
  warp/service.go
  warp/validators/state.go
  warp/validators/state_test.go
Labels: acp181
